services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: MyNotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mynotes:
    image: ${DOCKER_REGISTRY-}mynotes
    build:
      context: .
      dockerfile: MyNotes/Dockerfile
volumes:
  postgres-data: